name: "Get latest release tag"
description: "Gets the latest release tag of a github repository"
author: "Your name or organization here"

inputs:
  owner:
    description: The repository owner
    required: true
  repo:
    description: The repository name
    required: true
  by_date:
    description: Whether to sort releases by date or by tag
    required: false
    default: "false"
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
outputs:
  raw:
    description: "Raw tag retrieved from github"
  clean:
    description: "Tag cleaned"
  no_release:
    description: "Tag without release"
  clean_no_release:
    description: "Tag cleaned without release"
runs:
  using: "node16"
  main: "dist/index.js"
